name: 'LLM Code Review'
description: 'A container GitHub Action to review a pull request using OpenAI LLM Model.'
author: 'Louis Le (luiyen)'
inputs:
  githubToken:
    description: 'GitHub token to access the repo'
    required: true
  apiKey:
    description: 'OpenAI API key from [https://platform.openai.com/account/api-keys](https://platform.openai.com/account/api-keys)'
    required: true
  githubRepository:
    description: "The GitHub repository to use for the action"
    required: true
    default: "${{ github.repository }}"
  githubPullRequestNumber:
    description: "The GitHub pull request number to use for the action"
    required: true
    default: "${{ github.event.pull_request.number }}"
  gitCommitHash:
    description: "The GitHub commit hash to use for the action"
    required: true
    default: "${{ github.event.pull_request.head.sha }}"
  model:
    description: "OpenAI model to use"
    required: true
    default: "gpt-4o-mini"
  pullRequestDiff:
    description: "Pull request diff"
    required: true
  pullRequestChunkSize:
    description: "Pull request chunk size"
    required: false
    default: "3500"
  logLevel:
    description: "Log level"
    required: false
    default: "INFO"
runs:
  using: docker
  image: Dockerfile
  env:
    API_KEY: ${{ inputs.apiKey }}
    GITHUB_TOKEN: ${{ inputs.githubToken }}
    GITHUB_REPOSITORY: ${{ inputs.githubRepository }}
    GITHUB_PULL_REQUEST_NUMBER: ${{ inputs.githubPullRequestNumber }}
    GIT_COMMIT_HASH: ${{ inputs.gitCommitHash }}
  args:
    - "--model=${{ inputs.model }}"
    - "--diff-chunk-size=${{ inputs.pullRequestChunkSize }}"
    - "--diff=${{ inputs.pullRequestDiff }}"
    - "--log-level=${{ inputs.logLevel }}"
